Feature/show media from user posts
Islive/clubislive-api-client pull request #96
Opened 2018-07-11 10:33 UTC by twerohenrik

2018-07-11 10:34 UTC, twerohenrik commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add media from posts to Pictures/Videos](https://trello.com/c/ABNddcho/276-add-media-from-posts-to-pictures-videos)

2018-07-11 13:12 UTC, ghost approved these changes

2018-07-16 09:02 UTC, ghost approved these changes

2018-07-24 13:27 UTC, ghost approved these changes

2018-08-07 10:29 UTC, ghost requested changes

2018-08-07 10:29 UTC, pabloislive commented on api.js
> +        return this.get('rating/'+ model + '/' + foreignKey, callback);
Missing space before first plus sign

2018-08-07 11:20 UTC, ghost approved these changes

2018-08-08 06:19 UTC, merged

2018-08-16 07:14 UTC, sashaskr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove activity views](https://trello.com/c/Ft1nSqug/541-remove-activity-views)